name: auth_token_generator
description: A Dart package for generating and validating bearer tokens using HMAC-SHA256 encryption.
version: 1.2.0
repository: https://github.com/muhsindev4/auth_token_generator

environment:
  sdk: ^3.6.0
dependencies:
  crypto: ^3.0.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
